basic/profiles/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^edit/$',
        view    = 'basic.profiles.views.profile_edit',
        name    = 'profile_edit',
    ),
    url(r'^(?P<username>[-\w]+)/$',
        view    = 'basic.profiles.views.profile_detail',
        name    = 'profile_detail',
    ),
    url (r'^$',
        view    = 'basic.profiles.views.profile_list',
        name    = 'profile_list',
    ),
)

basic/profiles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.db.models import permalink
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import PhoneNumberField

import datetime
from dateutil import relativedelta
import re


class Profile(models.Model):
    """ Profile model """
    GENDER_CHOICES = (
        (1, 'Male'),
        (2, 'Female'),
    )
    user              = models.ForeignKey(User, unique=True)
    gender            = models.PositiveSmallIntegerField(_('gender'), choices=GENDER_CHOICES, blank=True, null=True)
    mugshot           = models.FileField(_('mugshot'), upload_to='mugshots', blank=True)
    birth_date        = models.DateField(_('birth date'), blank=True, null=True)
    address1          = models.CharField(_('address1'), blank=True, max_length=100)
    address2          = models.CharField(_('address2'), blank=True, max_length=100)
    city              = models.CharField(_('city'), blank=True, max_length=100)
    state             = models.CharField(_('state'), blank=True, max_length=100, help_text='or Province')
    zip               = models.CharField(_('zip'), blank=True, max_length=10)
    country           = models.CharField(_('country'), blank=True, max_length=100)
    mobile            = PhoneNumberField(_('mobile'), blank=True)
    mobile_provider   = models.ForeignKey('MobileProvider', blank=True, null=True)
  
    class Meta:
        verbose_name = _('user profile')
        verbose_name_plural = _('user profiles')
        db_table = 'user_profiles'

    def __unicode__(self):
        return u"%s" % self.user.get_full_name()
  
    @property
    def age(self):
        TODAY = datetime.date.today()
        if self.birth_date:
            return u"%s" % relativedelta.relativedelta(TODAY, self.birth_date).years
        else:
            return None

    @permalink
    def get_absolute_url(self):
        return ('profile_detail', None, { 'username': self.user.username })

    @property
    def sms_address(self):
        if (self.mobile and self.mobile_provider):
            return u"%s@%s" % (re.sub('-', '', self.mobile), self.mobile_provider.domain)


class MobileProvider(models.Model):
    """ MobileProvider model """
    title             = models.CharField(_('title'), max_length=25)
    domain            = models.CharField(_('domain'), max_length=50, unique=True)

    class Meta:
        verbose_name = _('mobile provider')
        verbose_name_plural = _('mobile providers')
        db_table = 'user_mobile_providers'

    def __unicode__(self):
        return u"%s" % self.title


class ServiceType(models.Model):
    """ Service type model """
    title           = models.CharField(_('title'), blank=True, max_length=100)
    url             = models.URLField(_('url'), blank=True, help_text='URL with a single \'{user}\' placeholder to turn a username into a service URL.', verify_exists=False)

    class Meta:
        verbose_name = _('service type')
        verbose_name_plural = _('service types')
        db_table = 'user_service_types'

    def __unicode__(self):
        return u"%s" % self.title


class Service(models.Model):
    """ Service model """
    service         = models.ForeignKey(ServiceType)
    profile         = models.ForeignKey(Profile)
    username        = models.CharField(_('Name or ID'), max_length=100, help_text="Username or id to be inserted into the service url.")
    created         = models.DateTimeField(auto_now_add=True)
    modified        = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = _('service')
        verbose_name_plural = _('services')
        db_table = 'user_services'
    
    def __unicode__(self):
        return u"%s" % self.username
    
    @property
    def service_url(self):
        return re.sub('{user}', self.username, self.service.url)
    
    @property
    def title(self):
        return u"%s" % self.service.title


class Link(models.Model):
    """ Service type model """
    profile         = models.ForeignKey(Profile)
    title           = models.CharField(_('title'), max_length=100)
    url             = models.URLField(_('url'), verify_exists=True)

    class Meta:
        verbose_name = _('link')
        verbose_name_plural = _('links')
        db_table = 'user_links'

    def __unicode__(self):
        return u"%s" % self.title

basic/profiles/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from django.contrib.auth.models import User
from basic.profiles.models import *


class ProfileForm(ModelForm):
    class Meta:
        model = Profile


ServiceFormSet  = inlineformset_factory(Profile, Service)
LinkFormSet     = inlineformset_factory(Profile, Link)


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

basic/profiles/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import Http404, HttpResponseRedirect
from django.views.generic import list_detail
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from basic.profiles.models import *
from basic.profiles.forms import *


def profile_list(request):
    return list_detail.object_list(
        request,
        queryset = Profile.objects.all(),
        paginate_by = 20,
    )
profile_list.__doc__ = list_detail.object_list.__doc__


def profile_detail(request, username):
    try:
        user = User.objects.get(username__iexact=username)
    except User.DoesNotExist:
        raise Http404
  
    profile = Profile.objects.get(user=user)
    context = { 'object':profile }
    return render_to_response('profiles/profile_detail.html', context, context_instance=RequestContext(request))
 

@login_required
def profile_edit(request, template_name='profiles/profile_form.html'):
    """Edit profile."""

    if request.POST:
        profile = Profile.objects.get(user=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        user_form = UserForm(request.POST, instance=request.user)
        service_formset = ServiceFormSet(request.POST, instance=profile)
        link_formset = LinkFormSet(request.POST, instance=profile)

        if profile_form.is_valid() and user_form.is_valid() and service_formset.is_valid() and link_formset.is_valid():
            profile_form.save()
            user_form.save()
            service_formset.save()
            link_formset.save()
            return HttpResponseRedirect(reverse('profile_detail', kwargs={'username': request.user.username}))
        else:
            context = {
                'profile_form': profile_form, 
                'user_form': user_form,
                'service_formset': service_formset,
                'link_formset': link_formset
            }
    else:
        profile = Profile.objects.get(user=request.user)
        service_formset = ServiceFormSet(instance=profile)
        link_formset = LinkFormSet(instance=profile)
        context = {
            'profile_form': ProfileForm(instance=profile), 
            'user_form': UserForm(instance=request.user),
            'service_formset': service_formset,
            'link_formset': link_formset
        }
    return render_to_response(template_name, context, context_instance=RequestContext(request))

basic/profiles/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body id="{% block body_id %}{% endblock %}">
  <div id="body">
    {% block body %}
      <div>
        {% block content_title %}{% endblock %}
      </div>
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
  </div>
</body>
</html>

basic/profiles/templates/profiles/base_profile.html
{% extends "base.html" %}


{% block body_class %}profiles{% endblock %}

basic/profiles/templates/profiles/profile_detail.html
{% extends "profiles/base_profile.html" %}


{% block title %}Profile for {{ object.user.get_full_name }}{% endblock %}


{% block content_title %}
  <h2 id="user_name">{{ object.user.get_full_name }}
    <em id="user_city">{{ object.city }}, {{ object.state }}</em></h2>
  <h3 id="user_age_and_gender">{{ object.get_gender_display }}{% if object.age %}, {{ object.age }}{% endif %}</h3>
{% endblock %}


{% block content %}
  {% if object.user.service_set.all %}
  <h3 class="list_title">Services</h3>
  <ul class="link_list">
    {% for service in object.user.service_set.all %}
    <li><a href="{{ service.service_url }}">{{ service.title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
  
  {% if object.user.link_set.all %}
  <h3 class="list_title">Links</h3>
  <ul class="link_list">
    {% for link in object.user.link_set.all %}
    <li><a href="{{ link.url }}">{{ link.title }}</a></li>
    {% endfor %}
  </ul>
  {% endif %}
{% endblock %}

basic/profiles/templates/profiles/profile_form.html
{% extends "base.html" %}


{% block title %}Profile form{% endblock %}


{% block content_title %}
  <h2>Profile form</h2>
{% endblock %}



{% block content %}
  <form action="." method="post" enctype="multipart/form-data" class="profile_form">
    <table>
      {{ user_form.as_table }}
      {{ profile_form.as_table }}
    </table>
    
    <fieldset>
      <h4>Other profiles <small>(e.g. Flickr, Twitter, etc.)</small></h4>
      {{ service_formset.management_form }}
      
      {% for form in service_formset.forms %}
      <ul class="service">
        {{ form.as_ul }}
      </ul>
      {% endfor %}
      
      <p class="quiet">To add more services than displayed save and continue editing.</p>
    </fieldset>
    
    <fieldset>
      <h4>Personal links <small>(Example: Your blog, you personal site, etc.)</small></h4>
      {{ link_formset.management_form }}
      
      {% for form in link_formset.forms %}
      <ul class="link">
        {{ form.as_ul }}
      </ul>
      {% endfor %}
      
      <p class="quiet">To add more links than displayed save and continue editing.</p>
    </fieldset>
    
    <p><input class="button" type="submit" value="Save"></p>
  </form>
{% endblock %}

basic/profiles/templates/profiles/profile_list.html
{% extends "profiles/base_profile.html" %}


{% block title %}Profiles{% endblock %}


{% block content_title %}
  <h2>User Profiles</h2>
{% endblock %}


{% block content %}
  <ul class="link_list">
    {% for profile in object_list %}
    <li><a href="{{ profile.get_absolute_url }}">{{ profile.user.get_full_name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}